#!/usr/bin/env python3
"""
Script to generate output.pdf as requested
"""

from fpdf import FPDF
from datetime import datetime

def generate_output_pdf():
    """Generate a PDF file named output.pdf with sample content"""
    
    # Create PDF object
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Add a page
    pdf.add_page()
    
    # Title
    pdf.set_font('Arial', 'B', 24)
    pdf.cell(0, 20, 'PDF Document', ln=True, align='C')
    
    # Subtitle
    pdf.set_font('Arial', 'I', 16)
    pdf.cell(0, 15, 'Generated with Python', ln=True, align='C')
    
    # Date
    pdf.set_font('Arial', '', 12)
    current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 10, f'Created on: {current_date}', ln=True, align='C')
    pdf.ln(20)
    
    # Main content
    pdf.set_font('Arial', 'B', 18)
    pdf.cell(0, 15, 'Content Section 1: Introduction', ln=True)
    
    pdf.set_font('Arial', '', 12)
    intro_text = """
This is a PDF document created programmatically using Python and the fpdf2 library.
The document was generated automatically and contains various types of content
to demonstrate PDF generation capabilities.
"""
    pdf.multi_cell(0, 8, intro_text)
    pdf.ln(10)
    
    # Section 2
    pdf.set_font('Arial', 'B', 18)
    pdf.cell(0, 15, 'Content Section 2: Features', ln=True)
    
    pdf.set_font('Arial', '', 12)
    features = [
        "Automatic text formatting",
        "Multiple font styles and sizes",
        "Page layout control",
        "Image embedding support",
        "Table creation capabilities",
        "Multi-page document support",
        "Headers and footers",
        "Custom page margins"
    ]
    
    for feature in features:
        pdf.cell(0, 8, f"• {feature}")
        pdf.ln()
    
    pdf.ln(10)
    
    # Section 3: Sample data table
    pdf.set_font('Arial', 'B', 18)
    pdf.cell(0, 15, 'Content Section 3: Sample Data', ln=True)
    
    # Table header
    pdf.set_font('Arial', 'B', 12)
    col_widths = [40, 40, 40, 40]
    headers = ['Item', 'Quantity', 'Unit Price', 'Total']
    
    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 10, header, border=1, align='C')
    pdf.ln()
    
    # Table data
    pdf.set_font('Arial', '', 12)
    data = [
        ['Product A', '5', '$10.00', '$50.00'],
        ['Product B', '3', '$15.00', '$45.00'],
        ['Product C', '8', '$7.50', '$60.00'],
        ['Product D', '2', '$25.00', '$50.00'],
        ['Product E', '12', '$4.99', '$59.88']
    ]
    
    for row in data:
        for i, item in enumerate(row):
            pdf.cell(col_widths[i], 10, item, border=1, align='C')
        pdf.ln()
    
    pdf.ln(20)
    
    # Final section
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 15, 'Document Summary', ln=True)
    
    pdf.set_font('Arial', '', 12)
    summary = """
This PDF document was generated to demonstrate the automated creation of 
PDF files using Python. The process is entirely programmatic and can be 
integrated into workflows for report generation, invoice creation, 
document automation, and more.
"""
    pdf.multi_cell(0, 8, summary)
    pdf.ln(10)
    
    # Footer
    pdf.set_font('Arial', 'I', 10)
    pdf.cell(0, 10, 'End of document - Generated by Python script', align='C')
    
    # Save the PDF
    output_filename = 'output.pdf'
    pdf.output(output_filename)
    
    return output_filename

if __name__ == "__main__":
    print("Generating output.pdf...")
    try:
        filename = generate_output_pdf()
        print(f"✓ Successfully created: {filename}")
        
        # Get file information
        import os
        if os.path.exists(filename):
            size = os.path.getsize(filename)
            print(f"✓ File size: {size} bytes ({size/1024:.1f} KB)")
            
            # Create a success marker file
            with open('pdf_generated_success.txt', 'w') as f:
                f.write(f"PDF generated successfully at {datetime.now()}\n")
                f.write(f"File: {filename}\n")
                f.write(f"Size: {size} bytes\n")
            
        print("\n✅ PDF generation completed successfully!")
        
    except Exception as e:
        print(f"❌ Error generating PDF: {e}")
        
        # Try a simpler fallback
        try:
            print("Trying fallback method...")
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font('Arial', 'B', 16)
            pdf.cell(0, 10, 'Simple PDF', ln=True, align='C')
            pdf.ln(10)
            pdf.set_font('Arial', '', 12)
            pdf.multi_cell(0, 10, 'Fallback PDF created successfully.')
            pdf.output('output.pdf')
            print("✓ Fallback PDF created: output.pdf")
        except Exception as e2:
            print(f"❌ Fallback also failed: {e2}")